### ISSUE TITLE
Somewhat support partial classes

### ISSUE THREAD

**Issue by Genmutant** [m31coding/M31.FluentAPI#15]
I have models for which i would like to generate builders. They are annotated to be [MemoryPackable](https://github.com/Cysharp/MemoryPack), which requires the types to be partial for the serializing stuff to be generated.

I get the error that partial classes aren't supported with FluentApi. Is there a problem with ignoring that, given that I won't use any stuff from the other parts for the builder?

In the README I couldn't find the exact reason why partial classes aren't supported.

**Comment by m31coding** [comment]
Hi, thank you for raising this issue. Currently, partial classes are not supported because I haven't yet examined all potential edge cases. I assume this shortcoming is difficult to ignore on your side, as no builder is generated due to the diagnostic error.

I agree that supporting partial classes would be very beneficial, and I will look into this within the next 2-3 weeks.

Best regards,
Kevin

**Comment by Genmutant** [comment]
> as no builder is generated due to the diagnostic error.

I'll have to see if I can just set the error to ignored when I'm back at work tomorrow.
Thanks for your fast answer!
