### ISSUE TITLE
Line Endings for test text is hardcoded

### ISSUE THREAD

**Issue by DerekGooding** [m31coding/M31.FluentAPI#21]
I had issues using this on windows platform because the tests looked for \r\n instead of \n. 

Suggest using System.Environment.NewLine as an alternative so that it is OS agnostic.

**Comment by m31coding** [comment]
Hi,

Thank you for this! You are right, there is a problem on Windows with the unit tests. Due to `text=auto` in the `.gitattributes` file, the line endings of the files `CreateStudent.expected.txt` are converted to CRLF on checkout on Windows.

I chose `\n` as the default line ending in the source generator to get deterministic behavior as per the recommendations. However, I think your solution to use `Environment.NewLine` is good and solves the issue.

Thanks for your contribution!
